def motif(seq, motif):
    locations = []
    motifLength = len(motif)

    i = motifLength
    while i <= len(seq):
        if seq[i-motifLength:i] == motif:
            locations.append(i-motifLength+1) # Add 1 since the correct answer is assumed to be 1-indexed
        i += 1
    
    return locations

print(motif("ACACGTCCAACTTCTCCAACTTCCAACTACACGTCCAACTCACTCCAACTCCGAGGTCCAACTGTGTCCAACTCTCCAACTCTCCAACTCGATCCAACTCTCCAACTTCCAACTTCCAACTTTCCAACTATCCAACTGCTCCAACTATCCAACTCCTCCAACTCAAGATCCAACTCTCCAACTCATAACGTCCAACTCTAGACTCCAACTGAGTGTCCAACTCCTCCAACTCTCCAACTGACTCGTCCAACTTCCAACTTCCAACTCTTGTCCAACTTAGATTCCAACTGTCCAACTCCACTCCAACTTCCAACTTCCAACTATCCAACTTTATATCCAACTGGCTAGGTTCCAACTAATAAACTCCAACTGGGAGTTTCCAACTCCATCCAACTATGTCCAACTTTTCGACTCCAACTATTCCAACTCTCCAACTAACTGGGTCCAACTGTCCAACTCGTCTCCAACTTCCAACTAATCCAACTTCCAACTTCTCCAACTTGCTCCAACTGATTCCAACTTGATCCAACTTCCAACTTCTCCAACTTCTCCAACTTTCCAACTGTCCAACTATCCAACTGTCCAACTATTTCCAACTTCCAACTTTATCCAACTCTCCAACTTCCAACTCAATCCAACTATTTTCCAACTTATCCAACTTAATCCAACTTCCAACTGTCCAACTTCCAACTTCCAACTTCCAACTTTTATTCCAACTTCCTCCAACTCAAGGCTCCAACTGGTTCCAACTTCCAACTTGCTCCAACTTAATTCCAACTTTCCAACTTCCAACTCTCCAACTGTCCAACTAGTCCAACTTCCAACTTTCCAACT", "TCCAACTTC"))
